name: villanakey
description: "Aplikasi reservasi villa."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.2.4
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  provider: ^6.0.0
  google_sign_in: ^6.3.0
  connectivity_plus: ^6.1.4
  shimmer: ^3.0.0
  fluttertoast: ^8.2.2
  http: ^0.13.6
  table_calendar: ^3.2.0
  intl: ^0.20.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logoya_app.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
  assets:
    - assets/images/
    - assets/icons/
