// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXktyaPGFWHei4CH_F3aH8uEmLac8Hx5I',
    appId: '1:154455470431:web:a7146ce74f608ee3d946ea',
    messagingSenderId: '154455470431',
    projectId: 'villanakey-17e14',
    authDomain: 'villanakey-17e14.firebaseapp.com',
    storageBucket: 'villanakey-17e14.firebasestorage.app',
    measurementId: 'G-LMJLY01KRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbzYVW7VUr10XHlndQuMnwTo71lE6jaZA',
    appId: '1:154455470431:android:76f0e62e0a00b159d946ea',
    messagingSenderId: '154455470431',
    projectId: 'villanakey-17e14',
    storageBucket: 'villanakey-17e14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsfLQwp8EFpmMfs1nhxPc7_-fc2aKHoIE',
    appId: '1:154455470431:ios:a6ddba6597d55939d946ea',
    messagingSenderId: '154455470431',
    projectId: 'villanakey-17e14',
    storageBucket: 'villanakey-17e14.firebasestorage.app',
    iosBundleId: 'com.example.villanakey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsfLQwp8EFpmMfs1nhxPc7_-fc2aKHoIE',
    appId: '1:154455470431:ios:a6ddba6597d55939d946ea',
    messagingSenderId: '154455470431',
    projectId: 'villanakey-17e14',
    storageBucket: 'villanakey-17e14.firebasestorage.app',
    iosBundleId: 'com.example.villanakey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXktyaPGFWHei4CH_F3aH8uEmLac8Hx5I',
    appId: '1:154455470431:web:7bcdc7d0c0107e3ad946ea',
    messagingSenderId: '154455470431',
    projectId: 'villanakey-17e14',
    authDomain: 'villanakey-17e14.firebaseapp.com',
    storageBucket: 'villanakey-17e14.firebasestorage.app',
    measurementId: 'G-K7NHYP8JP1',
  );
}
